import { Database } from "../types";

export const seedDb: Database = {
  users: [
    {
      id: "u1",
      role: "buyer",
      name: "Alex Rivera",
      phone: "300 123 4567",
      email: "alex@demo.com",
      password: "demo1234",
      createdAt: "2026-01-15T10:00:00Z",
      ratingAvg: 4.5,
      ratingCount: 2,
      department: "Meta",
      city: "Villavicencio",
      address: "Conjunto Los Cerezos, casa 186 Alborada",
      location: { lat: 4.1420, lng: -73.6266, address: "Conjunto Los Cerezos, Villavicencio" },
    },
    {
      id: "u2",
      role: "seller",
      name: "María López",
      phone: "310 987 6543",
      email: "maria@demo.com",
      password: "demo1234",
      createdAt: "2026-01-10T08:00:00Z",
      ratingAvg: 4.8,
      ratingCount: 5,
      department: "Antioquia",
      city: "Medellín",
      address: "Calle 10 #32-15",
      businessName: "Distribuidora María",
      location: { lat: 6.2442, lng: -75.5812, address: "Calle 10 #32-15, Medellín" },
    },
    {
      id: "u3",
      role: "seller",
      name: "Carlos Gómez",
      phone: "320 555 1234",
      email: "carlos@demo.com",
      password: "demo1234",
      createdAt: "2026-01-12T09:00:00Z",
      ratingAvg: 4.2,
      ratingCount: 3,
      department: "Antioquia",
      city: "Envigado",
      address: "Carrera 27 #38S-70",
      businessName: "TecnoCarlos",
      location: { lat: 6.1709, lng: -75.5830, address: "Carrera 27 #38S-70, Envigado" },
    },
    {
      id: "u4",
      role: "seller",
      name: "Laura Martínez",
      phone: "315 222 3333",
      email: "laura@demo.com",
      password: "demo1234",
      createdAt: "2026-01-14T11:00:00Z",
      ratingAvg: 4.6,
      ratingCount: 4,
      department: "Antioquia",
      city: "Medellín",
      address: "Avenida 80 #25-10",
      businessName: "Laura's Store",
      location: { lat: 6.2518, lng: -75.5936, address: "Avenida 80 #25-10, Medellín" },
    },
  ],
  products: [
    {
      id: "p1",
      sellerId: "u2",
      name: "Cerveza Corona x12",
      category: "Comida",
      priceBase: 45000,
      etaValue: 30,
      etaUnit: "min",
      notes: "Incluye hielo sin costo",
      images: [],
      createdAt: "2026-01-16T10:00:00Z",
    },
    {
      id: "p2",
      sellerId: "u2",
      name: "Whisky Johnnie Walker",
      category: "Comida",
      priceBase: 120000,
      etaValue: 1,
      etaUnit: "hours",
      images: [],
      createdAt: "2026-01-16T10:05:00Z",
    },
    {
      id: "p3",
      sellerId: "u3",
      name: "Smartphone Ultra X",
      category: "Electrónica",
      priceBase: 895000,
      etaValue: 2,
      etaUnit: "days",
      images: [],
      createdAt: "2026-01-17T10:00:00Z",
    },
    {
      id: "p4",
      sellerId: "u3",
      name: "Silla Pro Ergo",
      category: "Hogar",
      priceBase: 145000,
      etaValue: 3,
      etaUnit: "days",
      images: [],
      createdAt: "2026-01-17T10:05:00Z",
    },
    {
      id: "p5",
      sellerId: "u4",
      name: "Lámpara Nórdica",
      category: "Hogar",
      priceBase: 85000,
      etaValue: 1,
      etaUnit: "days",
      images: [],
      createdAt: "2026-01-18T10:00:00Z",
    },
    {
      id: "p6",
      sellerId: "u4",
      name: "Audífonos Beats",
      category: "Electrónica",
      priceBase: 310000,
      etaValue: 2,
      etaUnit: "days",
      images: [],
      createdAt: "2026-01-18T10:05:00Z",
    },
    {
      id: "p7",
      sellerId: "u4",
      name: "Café de Origen Huila",
      category: "Comida",
      priceBase: 35000,
      etaValue: 30,
      etaUnit: "min",
      images: [],
      createdAt: "2026-01-18T10:10:00Z",
    },
  ],
  requests: [
    {
      id: "r1",
      buyerId: "u1",
      title: "Cerveza Corona x12",
      description: "Necesito cerveza Corona caja de 12 unidades bien fría",
      quantity: 12,
      unit: "unidades",
      notes: "Entrega en portería, llamar al llegar",
      category: "Comida",
      location: { lat: 6.2442, lng: -75.5812, address: "Carrera 43A #1-50, Medellín" },
      status: "OPEN",
      createdAt: "2026-02-01T14:00:00Z",
    },
    {
      id: "r2",
      buyerId: "u1",
      title: "Reparación Pantalla iPhone 13",
      description: "Pantalla rota, necesito reparación urgente",
      quantity: 1,
      unit: "servicio",
      category: "Servicios",
      location: { lat: 6.2500, lng: -75.5700, address: "Centro Comercial Santafé" },
      status: "OPEN",
      createdAt: "2026-02-02T10:00:00Z",
    },
  ],
  offers: [
    {
      id: "o1",
      requestId: "r1",
      sellerId: "u2",
      price: 42000,
      etaValue: 25,
      etaUnit: "min",
      notes: "Incluye hielo y bolsa térmica",
      status: "SUBMITTED",
      createdAt: "2026-02-01T14:30:00Z",
    },
    {
      id: "o2",
      requestId: "r1",
      sellerId: "u4",
      price: 48000,
      etaValue: 40,
      etaUnit: "min",
      notes: "Entrega directa desde proveedor",
      status: "SUBMITTED",
      createdAt: "2026-02-01T15:00:00Z",
    },
    {
      id: "o3",
      requestId: "r2",
      sellerId: "u3",
      price: 180000,
      etaValue: 2,
      etaUnit: "hours",
      notes: "Garantía de 3 meses en la reparación",
      status: "SUBMITTED",
      createdAt: "2026-02-02T10:30:00Z",
    },
  ],
  chats: [],
  messages: [],
  ratings: [],
  passwordResets: [],
  notifications: [],
  counters: {
    users: 4,
    products: 7,
    requests: 2,
    offers: 3,
    chats: 0,
    messages: 0,
    ratings: 0,
    passwordResets: 0,
    notifications: 0,
  },
};
